// Every app's details in ONE place: id, title, icon, window size, whether the Start menu lists it, whether it
// opens once. The Start menu and the shell read this list; each app's code is loaded the first time it opens
// (LOADERS), so starting the desktop fetches the shell only, not every app (loading them all meant 105 scripts,
// 1.25 MB, before the desktop could be used). Each app file spreads its own entry (...APPS.<id>).
import type { AppDef, AppMeta } from '../shell/types.ts';

export const APPS = {
  explorer: { id: 'explorer', title: 'File Explorer', icon: 'files', size: [640, 440], start: true },
  editor: { id: 'editor', title: 'Notepad', icon: 'editor', size: [680, 480], start: true },
  notepadpro: { id: 'notepadpro', title: 'Notepad Pro', icon: 'code', size: [900, 580], minSize: [420, 300], start: true },
  calculator: { id: 'calculator', title: 'Calculator', icon: 'calculator', size: [296, 460], minSize: [280, 400], start: true },
  photoedit: { id: 'photoedit', title: 'Photo Editor', icon: 'photoedit', size: [980, 660], minSize: [480, 360], start: true },
  photos: { id: 'photos', title: 'Pictures', icon: 'photos', size: [680, 520] },
  player: { id: 'player', title: 'Player', icon: 'player', size: [560, 400] },
  pdf: { id: 'pdf', title: 'PDF Viewer', icon: 'pdfviewer', size: [720, 560] },
  sheet: { id: 'sheet', title: 'Spreadsheet', icon: 'sheet', size: [960, 620], minSize: [560, 360], start: true },
  calendar: { id: 'calendar', title: 'Calendar', icon: 'calendar', size: [820, 560], minSize: [360, 380], start: true },
  contacts: { id: 'contacts', title: 'Contacts', icon: 'contacts', size: [720, 500], minSize: [360, 320], start: true },
  mail: { id: 'mail', title: 'Mail', icon: 'mail', size: [1120, 680], minSize: [520, 360], start: true, single: true },
  mailcompose: { id: 'mailcompose', title: 'New message', icon: 'mail', size: [720, 560], minSize: [420, 360] },
  chat: { id: 'chat', title: 'Chat', icon: 'chat', size: [460, 600], minSize: [320, 360], start: true, single: true },
  panel: { id: 'panel', title: 'Panel', icon: 'panel', size: [1180, 720], minSize: [640, 420], start: true, single: true },
  reader: { id: 'reader', title: 'Reader', icon: 'book', size: [1100, 720], minSize: [360, 380], start: true, single: true },
  appmanager: { id: 'appmanager', title: 'Application manager', icon: 'app', size: [860, 580], minSize: [380, 340], start: true, single: true },
  aimodels: { id: 'aimodels', title: 'Find AI models', icon: 'modelsearch', size: [900, 640], minSize: [380, 360], start: true, single: true },
  archive: { id: 'archive', title: 'Archive Opener', icon: 'archive', size: [620, 440] },
  riscv: { id: 'riscv', title: 'RISC-V Studio', icon: 'chip', size: [1120, 680], minSize: [520, 360], start: true },
  planetziods: { id: 'planetziods', title: 'Planetziods', icon: 'planet', size: [1000, 660], minSize: [560, 420], start: true, single: true },
  printer: { id: 'printer', title: 'Office Printer', icon: 'printer', size: [560, 680], minSize: [340, 440], start: true, single: true },
  terminal: { id: 'terminal', title: 'Terminal', icon: 'terminal', size: [760, 480], minSize: [320, 200], start: true },
  link: { id: 'link', title: 'Web link', icon: 'link', size: [460, 230], minSize: [320, 200] },
  trash: { id: 'trash', title: 'Recycle Bin', icon: 'trash', size: [620, 380], start: true, single: true },
  taskmanager: { id: 'taskmanager', title: 'Task Manager', icon: 'gear', size: [560, 480], minSize: [360, 320], start: true, single: true },
  settings: { id: 'settings', title: 'Settings', icon: 'gear', size: [560, 640], minSize: [320, 300], start: true, single: true },
  account: { id: 'account', title: 'My account', icon: 'user', size: [560, 640], minSize: [340, 320], start: true, single: true },
  shortcuts: { id: 'shortcuts', title: 'Keyboard shortcuts', icon: 'keyboard', size: [560, 520], minSize: [320, 240], start: true, single: true },
  about: { id: 'about', title: 'About MyiaOS', icon: 'info', size: [560, 520], minSize: [320, 300], start: true, single: true },
} as const satisfies Record<string, AppMeta>;

export type AppId = keyof typeof APPS;

/** Loads an app's code (once; the browser keeps the module). */
export const LOADERS: Record<AppId, () => Promise<AppDef>> = {
  explorer: () => import('./explorer.ts').then(m => m.explorerApp),
  editor: () => import('./editor.ts').then(m => m.editorApp),
  notepadpro: () => import('./notepadpro.ts').then(m => m.notepadProApp),
  calculator: () => import('./calculator.ts').then(m => m.calculatorApp),
  photoedit: () => import('./photoedit.ts').then(m => m.photoEditApp),
  photos: () => import('./photos.ts').then(m => m.photosApp),
  player: () => import('./player.ts').then(m => m.playerApp),
  pdf: () => import('./pdf.ts').then(m => m.pdfApp),
  sheet: () => import('./sheet.ts').then(m => m.sheetApp),
  calendar: () => import('./calendar.ts').then(m => m.calendarApp),
  contacts: () => import('./contacts.ts').then(m => m.contactsApp),
  mail: () => import('./mail.ts').then(m => m.mailApp),
  mailcompose: () => import('./mail/compose.ts').then(m => m.composeApp),
  chat: () => import('./chat.ts').then(m => m.chatApp),
  panel: () => import('./panel.ts').then(m => m.panelApp),
  reader: () => import('./reader.ts').then(m => m.readerApp),
  appmanager: () => import('./appmanager.ts').then(m => m.appManagerApp),
  aimodels: () => import('./aimodels.ts').then(m => m.aiModelsApp),
  archive: () => import('./archive.ts').then(m => m.archiveApp),
  riscv: () => import('./riscv.ts').then(m => m.riscvApp),
  planetziods: () => import('./planetziods.ts').then(m => m.planetziodsApp),
  printer: () => import('./printer.ts').then(m => m.printerApp),
  terminal: () => import('./terminal.ts').then(m => m.terminalApp),
  link: () => import('./link.ts').then(m => m.linkApp),
  trash: () => import('./recyclebin.ts').then(m => m.recycleBinApp),
  taskmanager: () => import('./taskmanager.ts').then(m => m.taskManagerApp),
  settings: () => import('./settings.ts').then(m => m.settingsApp),
  account: () => import('./account.ts').then(m => m.accountApp),
  shortcuts: () => import('./shortcuts.ts').then(m => m.shortcutsApp),
  about: () => import('./about.ts').then(m => m.aboutApp),
};
